Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -59,21 +59,20 @@ jobs:
       - name: Check out Git Repository
         uses: actions/checkout@v3
 
-      - name: Run TFSec and save output
-        id: tfsec
-        run: |
-          tfsec --format sarif ./Terraform_code > tfsec_output.sarif.txt 2>&1 || true
+      - name: Run Tfsec
+        uses: aquasecurity/tfsec-action@v1.0.0
 
-      - name: Filter Failure Cases from TFSec Output
-        run: grep -E "CRITICAL|HIGH" tfsec_output.sarif.txt > tfsec-failures.txt || true
 
-      - name: TFSec Output in PR
-        uses: marocchino/sticky-pull-request-comment@v2
-        with:
-          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-          header: tfsec-outputs
-          recreate: true
-          path: tfsec-failures.txt
+      # - name: Filter Failure Cases from TFSec Output
+      #   run: grep -E "CRITICAL|HIGH" tfsec_output.sarif.txt > tfsec-failures.txt || true
+
+      # - name: TFSec Output in PR
+      #   uses: marocchino/sticky-pull-request-comment@v2
+      #   with:
+      #     GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+      #     header: tfsec-outputs
+      #     recreate: true
+      #     path: tfsec-failures.txt
 
   checkov-check:
     runs-on: ubuntu-latest
@@ -85,18 +84,18 @@ jobs:
       - name: Test with Checkov
         id: checkov
         uses: bridgecrewio/checkov-action@master
-        continue-on-error: true
+        # continue-on-error: true
 
-      - name: Checkov Output in PR
-        uses: marocchino/sticky-pull-request-comment@v2
-        with:
-          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
-          header: checkov-outputs
-          recreate: true
-          message: |
-            ```
-            ${{ steps.checkov.outputs.checkov_output }}
-            ```
+      # - name: Checkov Output in PR
+      #   uses: marocchino/sticky-pull-request-comment@v2
+      #   with:
+      #     GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
+      #     header: checkov-outputs
+      #     recreate: true
+      #     message: |
+      #       ```
+      #       ${{ steps.checkov.outputs.checkov_output }}
+      #       ```
 
   format-terraform:
     runs-on: ubuntu-latest
